In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
# pip nbextensions

In [2]:
credit_card_balance= pd.read_csv("credit_card_balance.csv")
#previous_application = pd.read_csv("previous_application.csv")

# 欄位介紹看csv檔
# 首先以整張表來看

In [19]:
credit_card_balance.sort_values(by=['SK_ID_CURR','SK_ID_PREV'])
#384萬筆資料，23欄位

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
584804,1489396,100006,-1,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248506,1794451,456250,-7,174435.885,180000,0.0,0.0,0.0,0.0,9240.705,...,174435.885,174435.885,0.0,0,0.0,0.0,4.0,Active,0,0
2985617,1794451,456250,-8,177219.000,180000,0.0,0.0,0.0,0.0,9465.705,...,176958.900,176958.900,0.0,0,0.0,0.0,3.0,Active,0,0
3000394,1794451,456250,-12,181993.500,180000,171000.0,171000.0,0.0,0.0,0.000,...,171000.000,171000.000,7.0,7,0.0,0.0,0.0,Active,0,0
3611324,1794451,456250,-11,200208.915,180000,9000.0,9000.0,0.0,0.0,0.000,...,196581.915,196581.915,1.0,1,0.0,0.0,0.0,Active,0,0
3734047,1794451,456250,-9,180536.760,180000,0.0,0.0,0.0,0.0,9653.985,...,179866.260,179866.260,0.0,0,0.0,0.0,2.0,Active,0,0

In [20]:
# 總行數
row_total = credit_card_balance.shape[0]

In [21]:
# 遺失值比率
# 全部遺失值不超過20% 
nan_rows_sum = credit_card_balance.isna().sum()/row_total
max_nan_percentage = nan_rows_sum.max()
min_nan_percentage = nan_rows_sum.min()
print("最大遺失值佔比:", max_nan_percentage)
print("-"*80)
print(nan_rows_sum)

最大遺失值佔比: 0.19998062657409085
--------------------------------------------------------------------------------
SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.000000
AMT_CREDIT_LIMIT_ACTUAL       0.000000
AMT_DRAWINGS_ATM_CURRENT      0.195249
AMT_DRAWINGS_CURRENT          0.000000
AMT_DRAWINGS_OTHER_CURRENT    0.195249
AMT_DRAWINGS_POS_CURRENT      0.195249
AMT_INST_MIN_REGULARITY       0.079482
AMT_PAYMENT_CURRENT           0.199981
AMT_PAYMENT_TOTAL_CURRENT     0.000000
AMT_RECEIVABLE_PRINCIPAL      0.000000
AMT_RECIVABLE                 0.000000
AMT_TOTAL_RECEIVABLE          0.000000
CNT_DRAWINGS_ATM_CURRENT      0.195249
CNT_DRAWINGS_CURRENT          0.000000
CNT_DRAWINGS_OTHER_CURRENT    0.195249
CNT_DRAWINGS_POS_CURRENT      0.195249
CNT_INSTALMENT_MATURE_CUM     0.079482
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.000000
SK_DPD_DEF                    0.000000
dtype: float64

In [22]:
# 0的比率
zero_rows_sum = (credit_card_balance == 0).sum()/row_total
print(zero_rows_sum)
#print("-"*80)
#print(zero_rows_sum.describe())

SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.561522
AMT_CREDIT_LIMIT_ACTUAL       0.196292
AMT_DRAWINGS_ATM_CURRENT      0.694141
AMT_DRAWINGS_CURRENT          0.839370
AMT_DRAWINGS_OTHER_CURRENT    0.801540
AMT_DRAWINGS_POS_CURRENT      0.735772
AMT_INST_MIN_REGULARITY       0.502268
AMT_PAYMENT_CURRENT           0.101686
AMT_PAYMENT_TOTAL_CURRENT     0.565637
AMT_RECEIVABLE_PRINCIPAL      0.597912
AMT_RECIVABLE                 0.550428
AMT_TOTAL_RECEIVABLE          0.550383
CNT_DRAWINGS_ATM_CURRENT      0.694141
CNT_DRAWINGS_CURRENT          0.841065
CNT_DRAWINGS_OTHER_CURRENT    0.801416
CNT_DRAWINGS_POS_CURRENT      0.735772
CNT_INSTALMENT_MATURE_CUM     0.143600
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.960067
SK_DPD_DEF                    0.976736
dtype: float64

In [44]:
#各欄位最大值
credit_card_balance.max()

SK_ID_PREV                        2843496
SK_ID_CURR                         456250
MONTHS_BALANCE                         -1
AMT_BALANCE                   1505902.185
AMT_CREDIT_LIMIT_ACTUAL           1350000
AMT_DRAWINGS_ATM_CURRENT        2115000.0
AMT_DRAWINGS_CURRENT          2287098.315
AMT_DRAWINGS_OTHER_CURRENT      1529847.0
AMT_DRAWINGS_POS_CURRENT       2239274.16
AMT_INST_MIN_REGULARITY        202882.005
AMT_PAYMENT_CURRENT           4289207.445
AMT_PAYMENT_TOTAL_CURRENT      4278315.69
AMT_RECEIVABLE_PRINCIPAL      1472316.795
AMT_RECIVABLE                 1493338.185
AMT_TOTAL_RECEIVABLE          1493338.185
CNT_DRAWINGS_ATM_CURRENT             51.0
CNT_DRAWINGS_CURRENT                  165
CNT_DRAWINGS_OTHER_CURRENT           12.0
CNT_DRAWINGS_POS_CURRENT            165.0
CNT_INSTALMENT_MATURE_CUM           120.0
NAME_CONTRACT_STATUS               Signed
SK_DPD                               3260
SK_DPD_DEF                           3260
dtype: object

In [45]:
#各欄位最小值
credit_card_balance.min()

SK_ID_PREV                       1000018
SK_ID_CURR                        100006
MONTHS_BALANCE                       -96
AMT_BALANCE                  -420250.185
AMT_CREDIT_LIMIT_ACTUAL                0
AMT_DRAWINGS_ATM_CURRENT        -6827.31
AMT_DRAWINGS_CURRENT            -6211.62
AMT_DRAWINGS_OTHER_CURRENT           0.0
AMT_DRAWINGS_POS_CURRENT             0.0
AMT_INST_MIN_REGULARITY              0.0
AMT_PAYMENT_CURRENT                  0.0
AMT_PAYMENT_TOTAL_CURRENT            0.0
AMT_RECEIVABLE_PRINCIPAL      -423305.82
AMT_RECIVABLE                -420250.185
AMT_TOTAL_RECEIVABLE         -420250.185
CNT_DRAWINGS_ATM_CURRENT             0.0
CNT_DRAWINGS_CURRENT                   0
CNT_DRAWINGS_OTHER_CURRENT           0.0
CNT_DRAWINGS_POS_CURRENT             0.0
CNT_INSTALMENT_MATURE_CUM            0.0
NAME_CONTRACT_STATUS              Active
SK_DPD                                 0
SK_DPD_DEF                             0
dtype: object

In [123]:
# 發現描述裡"AMT_RECIVABLE"與"AMT_TOTAL_RECEIVABLE" 極度相似
matching_count = (credit_card_balance['AMT_RECIVABLE'] == credit_card_balance['AMT_TOTAL_RECEIVABLE']).sum()
print("相同的百分比:", matching_count/row_total)
print("選擇drop掉其一")
print("-"*80)
RE_NAN=credit_card_balance["AMT_RECIVABLE"].isna().sum()/row_total
RE_ZERO=(credit_card_balance["AMT_RECIVABLE"] == 0).sum()/row_total
RETOTAL_NAN=credit_card_balance["AMT_TOTAL_RECEIVABLE"].isna().sum()/row_total
RETOTAL_ZERO=(credit_card_balance["AMT_TOTAL_RECEIVABLE"] == 0).sum()/row_total
print("AMT_RECIVABLE 遺失值為 : ",RE_NAN)
print("AMT_TOTAL_RECEIVABLE 遺失值為 : ",RETOTAL_NAN)
print("-"*80)
print("AMT_RECIVABLE        0值為 : ",RE_ZERO)
print("AMT_TOTAL_RECEIVABLE 0值為 : ",RETOTAL_ZERO)
print("-"*80)
print("所以drop掉0值比較多的AMT_Recivable")

相同的百分比: 0.9970721128908276
選擇drop掉其一
--------------------------------------------------------------------------------
AMT_RECIVABLE 遺失值為 :  0.0
AMT_TOTAL_RECEIVABLE 遺失值為 :  0.0
--------------------------------------------------------------------------------
AMT_RECIVABLE        0值為 :  0.5504281943758736
AMT_TOTAL_RECEIVABLE 0值為 :  0.5503831459527246
--------------------------------------------------------------------------------
所以drop掉0值比較多的AMT_Recivable

In [145]:
matching_count_C = (credit_card_balance['AMT_PAYMENT_CURRENT'] == credit_card_balance['AMT_PAYMENT_TOTAL_CURRENT']).sum()
print("相同的百分比:", matching_count_C/row_total)

相同的百分比: 0.49086949185378687

# 觀察各個欄位 (含離群值)

In [136]:
#AMT_BALANCE

#有幾種類別
#是數值資料就再做簡單的觀察
# case1 drop掉小於0的重新算IQR、STD
# case2 將小於0的視為不小心打負數了，再重新算IQR、STD

colume = 'AMT_BALANCE'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(credit_card_balance[colume].max()))
print("最大值 : {}".format(credit_card_balance[colume].min()))

print("小於0的比數：", (np.sum(MONTHS_BALANCE_Sort_Categories<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------
最大值 : 1505902.185
最大值 : -420250.185
小於0的比數： 793
Q1 : 62775.36
Q3 : 182538.91125
平均值 : 148176.77570418583
正三倍標準差 : 540870.66272887 負三倍標準差 : -244517.11132049834
--------------------------------------------------------------------------------
Case1(3倍標準差)離群值個數： 23373
Case1(3倍標準差)離群值%： 0.006086224244280152
--------------------------------------------------------------------------------
Case2(IQR(1.5倍)離群值個數： 108076
Case2(IQR(1.5倍)離群值%： 2.8142505088128256

In [137]:
#AMT_CREDIT_LIMIT_ACTUAL

#有幾種類別
#是數值資料就再做簡單的觀察
colume = 'AMT_CREDIT_LIMIT_ACTUAL'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(credit_card_balance[colume].max()))
print("最大值 : {}".format(credit_card_balance[colume].min()))

print("小於0的比數：", (np.sum(MONTHS_BALANCE_Sort_Categories<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------
最大值 : 1350000
最大值 : 0
小於0的比數： 0
Q1 : 202500.0
Q3 : 616500.0
平均值 : 420265.19337016577
正三倍標準差 : 1213773.7162557533 負三倍標準差 : -373243.32951542165
--------------------------------------------------------------------------------
Case1(3倍標準差)離群值個數： 2
Case1(3倍標準差)離群值%： 5.207910190630345e-07
--------------------------------------------------------------------------------
Case2(IQR(1.5倍)離群值個數： 1
Case2(IQR(1.5倍)離群值%： 2.6039550953151726e-05

In [141]:
#AMT_DRAWINGS_ATM_CURRENT

#有幾種類別
#是數值資料就再做簡單的觀察
colume = 'AMT_DRAWINGS_ATM_CURRENT'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(credit_card_balance[colume].max()))
print("最大值 : {}".format(credit_card_balance[colume].min()))

print("小於0的比數：", (np.sum(credit_card_balance[colume]<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------
最大值 : 2115000.0
最大值 : -6827.31
小於0的比數： 1
Q1 : nan
Q3 : nan
平均值 : nan
正三倍標準差 : nan 負三倍標準差 : nan
--------------------------------------------------------------------------------
Case1(3倍標準差)離群值個數： 0
Case1(3倍標準差)離群值%： 0.0
--------------------------------------------------------------------------------
Case2(IQR(1.5倍)離群值個數： 0
Case2(IQR(1.5倍)離群值%： 0.0

In [142]:
#AMT_DRAWINGS_CURRENT

#有幾種類別
#是數值資料就再做簡單的觀察

#小於0不合理我認為drop掉小於0的重新算IQR、STD

colume = 'AMT_DRAWINGS_CURRENT'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(credit_card_balance[colume].max()))
print("最大值 : {}".format(credit_card_balance[colume].min()))

print("小於0的比數：", (np.sum(MONTHS_BALANCE_Sort_Categories<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------
最大值 : 2287098.315
最大值 : -6211.62
小於0的比數： 3
Q1 : 11042.82
Q3 : 83206.71
平均值 : 65421.967265500934
正三倍標準差 : 345435.3301683618 負三倍標準差 : -214591.39563735994
--------------------------------------------------------------------------------
Case1(3倍標準差)離群值個數： 3821
Case1(3倍標準差)離群值%： 0.0009949712419199273
--------------------------------------------------------------------------------
Case2(IQR(1.5倍)離群值個數： 13717
Case2(IQR(1.5倍)離群值%： 0.35718452042438215

In [143]:
#AMT_DRAWINGS_OTHER_CURRENT

#有幾種類別
#是數值資料就再做簡單的觀察

#小於0不合理我認為drop掉小於0的重新算IQR、STD

colume = 'AMT_DRAWINGS_OTHER_CURRENT'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(credit_card_balance[colume].max()))
print("最大值 : {}".format(credit_card_balance[colume].min()))

print("小於0的比數：", (np.sum(MONTHS_BALANCE_Sort_Categories<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------
最大值 : 1529847.0
最大值 : 0.0
小於0的比數： 0
Q1 : nan
Q3 : nan
平均值 : nan
正三倍標準差 : nan 負三倍標準差 : nan
--------------------------------------------------------------------------------
Case1(3倍標準差)離群值個數： 0
Case1(3倍標準差)離群值%： 0.0
--------------------------------------------------------------------------------
Case2(IQR(1.5倍)離群值個數： 0
Case2(IQR(1.5倍)離群值%： 0.0

In [133]:
#AMT_DRAWINGS_POS_CURRENT

#有幾種類別
#是數值資料就再做簡單的觀察

#小於0不合理我認為drop掉小於0的重新算IQR、STD

colume = 'AMT_DRAWINGS_POS_CURRENT'
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=[colume],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort[colume].unique()
#print(MONTHS_BALANCE_Sort_Categories)

num_categories = len(MONTHS_BALANCE_Sort_Categories)
#print("總共有", num_categories, "種分類")
print("-"*80)

print("最大值 : {}".format(np.max(MONTHS_BALANCE_Sort)))
print("最大值 : {}".format(np.percentile(MONTHS_BALANCE_Sort,100)))
print("最小值 : {}".format(np.percentile(MONTHS_BALANCE_Sort,0)))

print("小於0的比數：", (np.sum(MONTHS_BALANCE_Sort_Categories<0)))

q1 = np.percentile(MONTHS_BALANCE_Sort_Categories, 25)
q3 = np.percentile(MONTHS_BALANCE_Sort_Categories, 75)
print("Q1 : {} ".format(q1))
print("Q3 : {} ".format(q3))
# mode_value = stats.mode(MONTHS_BALANCE_Sort_Categories)
# mode = mode_value.mode[0]
# count = mode_value.count[0]
# print(mode)
# print(count)

MONTHS_BALANCE_STD = np.std(MONTHS_BALANCE_Sort_Categories)
MONTHS_BALANCE_MEAN = np.mean(MONTHS_BALANCE_Sort_Categories)
print("平均值 : {}".format(MONTHS_BALANCE_MEAN))
UCL=MONTHS_BALANCE_MEAN+MONTHS_BALANCE_STD*3
LCL=MONTHS_BALANCE_MEAN-MONTHS_BALANCE_STD*3
print("正三倍標準差 : {}".format(UCL),"負三倍標準差 : {}".format(LCL))

print("-"*80)
print("Case1(3倍標準差)離群值個數：", np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))
print("Case1(3倍標準差)離群值%：", (np.sum(MONTHS_BALANCE_Sort_Categories>UCL)+np.sum(MONTHS_BALANCE_Sort_Categories<LCL))/row_total)

print("-"*80)
IQR=q3-q1
case2_outliers = np.sum((MONTHS_BALANCE_Sort_Categories > q3 + 1.5 * IQR) | (MONTHS_BALANCE_Sort_Categories < q1 - 1.5 * IQR))
print("Case2(IQR(1.5倍)離群值個數：", case2_outliers)
print("Case2(IQR(1.5倍)離群值%：", (case2_outliers / row_total) * 100)

--------------------------------------------------------------------------------

TypeError: '>=' not supported between instances of 'float' and 'str'

# 0要drop掉還是怎麼補

# 第一種探索 (0要drop掉還是怎麼補)

In [ ]:
# 我想做一個簡單的function去跑 
# 有什麼類別、佔比多少|遺失值比率|0的比率|最大最小值

# def check(a):
#     c= a.sort_values(by=[0],ascending=False)
#     d = c[0].unique()
#     print(c)

In [ ]:
# row全取,留第一個欄位
credit_card_balance.iloc[:,0:1]

In [ ]:

# 看Active佔的總比數
Boolin = credit_card_balance['NAME_CONTRACT_STATUS']=='Active'
print(Boolin.sum()/row_total)

In [122]:
# 原本想用圖型呈現
# 抓出名稱為"AMT_BALANCE"的欄位
#column_name = 'AMT_BALANCE'
#selected_column = credit_card_balance[column_name]

# 提取Y軸數值
#y_values = selected_column.values
# 創建X軸的數據
#x_values = range(1, len(y_values) + 1)

# 繪製折線圖
#plt.plot(x_values, y_values, marker='')

# 設置X軸刻度
#x_tick_interval = 100  # 設定刻度的間隔
#plt.xticks(x_values[::x_tick_interval])

# 設置圖表標籤和標題
#plt.xlabel('Row')
#plt.ylabel(column_name)
#plt.title(f"折線圖 - {column_name}")

# 自動調整佈局
#plt.tight_layout()

# 顯示圖表
#plt.show()

# 第二種探索 延伸新欄位

# 命題1:
#           AMT_INST_MIN_REGULARITY(上期信用卡應付最小金額)
#           AMT_PAYMENT_CURRENT(實際上客戶在上期信用卡還款多少)
#          這兩個的關係我認為可以生出一個欄位
#          AMT_TOTAL_RECEIVABLE(該繳金額)
#
#          1.實際上還款多少>該期貸款金額-應付最小金額/2+應付最小金額 *算正常還款
#
#          2.實際上還款多少<該期貸款金額-應付最小金額/2+應付最小金額 
#          至實際上還款多少>=應付最小金額  *算能賺利息是更好的還款
#
#          3.實際上還款多少<應付最小金額 *BAD

In [ ]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

df1= pd.read_csv("credit_card_balance.csv")

#依照昨天的想法 可以drop掉
#好幾個欄位 待會補上

#確認負數
real_pay=df1['AMT_PAYMENT_CURRENT']
#print((real_pay < 0).sum())
should_pay=df1['AMT_TOTAL_RECEIVABLE']
#print((should_pay < 0).sum())
min_should_pay=df1['AMT_INST_MIN_REGULARITY']
#print((min_should_pay < 0).sum())

###############################################
#real_pay 遺失值約20%，10%是0，負數有0個
#10%為0不處理 我認為合裡上期沒有付款而已，沒有負數是正常值
#遺失值我想用<平均數去填>
real_pay_mean_value = real_pay.mean()
real_pay.fillna(real_pay_mean_value, inplace=True)

#檢測是否補值完

#print(real_pay.isnull().sum())
#print((real_pay==0).sum())

###############################################
#should_pay 沒有遺失值，55%是0，負數有109330個
#負數有10萬筆我視為寫錯將<負數轉為正數>
#55%是0 不太合理 應付款項不應該為0 <用平均數去補值>

#轉正數
should_pay = should_pay.abs()

#確認平均數、中位數
#print(should_pay.mean()) 
#print(should_pay.median())

#檢測補0前補0後
#print((should_pay==0).sum())
should_pay[should_pay == 0]=should_pay.mean()
#print((should_pay==0).sum())

###############################################
#min_should_pay 遺失值8%，50%是0，負數有0個
#55%是0 不太合理 最小應付款項不應該為0  <用平均數補值>
#我的做法是先用平均數補0 再去把新的資料平均數之後補遺失值

#檢測補0前補0後
#print((min_should_pay==0).sum())
min_should_pay[min_should_pay == 0]=min_should_pay.mean()
#print((min_should_pay==0).sum())

#檢測補遺失值前後
#print(min_should_pay.isnull().sum())
min_should_pay.fillna(min_should_pay.mean(), inplace=True)
#print(min_should_pay.isnull().sum())


df1['creditcard_normal_pay'] = (real_pay>(((should_pay-min_should_pay)/2)+min_should_pay))==True
df1['creditcard_nice_pay'] = ((real_pay<(((should_pay-min_should_pay)/2)+min_should_pay))&(real_pay>min_should_pay))==True
df1['creditcard_bad_pay'] = (real_pay<min_should_pay)==True

#檢測單熱是否做完
"""
print(df1['creditcard_normal_pay'].head())
print('-'*80)
print(df1['creditcard_nice_pay'].head())
print('-'*80)
print(df1['creditcard_bad_pay'].head())
print('-'*80)
normal_true = df1['creditcard_normal_pay'].sum()
print(normal_true)
print(normal_true/df1.shape[0])
nice_true = df1['creditcard_nice_pay'].sum()
print(nice_true)
print(nice_true/df1.shape[0])
bad_true = df1['creditcard_bad_pay'].sum()
print(bad_true)
print(bad_true/df1.shape[0])
"""

df2= pd.read_csv("application_train.csv")

#檢測column前後
#print(df2.columns)
new_columns = df1[['AMT_PAYMENT_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_INST_MIN_REGULARITY']]

df2 = pd.concat([df2,new_columns],axis=1)
print(df2.columns)

C:\Users\dimon\AppData\Local\Temp\ipykernel_17192\2579490310.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  min_should_pay[min_should_pay == 0]=min_should_pay.mean()

In [42]:
print(df2.columns)
print(len(df2.columns))

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [43]:
new_columns = df1[['AMT_PAYMENT_CURRENT', 'AMT_TOTAL_RECEIVABLE', 'AMT_INST_MIN_REGULARITY']]

df2 = pd.concat([df2,new_columns],axis=1)
print(df2.columns)
print(len(df2.columns))

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'AMT_PAYMENT_CURRENT',
       'AMT_TOTAL_RECEIVABLE', 'AMT_INST_MIN_REGULARITY'],
      dtype='object', length=125)

# 命題2:
#           CNT_INSTALMENT_MATURE_CUM(信用卡(上期)貸款已支付分期付款的次數)
#           找到該筆貸款的總期數去做切割，分成剛(開始還、還一半、還差不多)
#           這樣就可以做針對某期看各客戶的還款狀態去比 現在說的分類
#           看跟(train那張表)有沒有高度正相關

# 命題3:
#           MONTHS_BALANCE貸款申請日期(-1為上一期，-2為上上期，數字越大離越遠)
#           可以看時期 切割時期去看有沒有時間背景造成的還款NONO的狀況

# AMT_PAYMENT_CURRENT
# AMT_PAYMENT_TOTAL_CURRENT