In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
# pip nbextensions

In [3]:
credit_card_balance= pd.read_csv("credit_card_balance.csv")
#previous_application = pd.read_csv("previous_application.csv")

# 欄位介紹看csv檔
# 首先以整張表來看

In [4]:
credit_card_balance.sort_values(by=['SK_ID_CURR','SK_ID_PREV'])
#384萬筆資料，23欄位

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
584804,1489396,100006,-1,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248506,1794451,456250,-7,174435.885,180000,0.0,0.0,0.0,0.0,9240.705,...,174435.885,174435.885,0.0,0,0.0,0.0,4.0,Active,0,0
2985617,1794451,456250,-8,177219.000,180000,0.0,0.0,0.0,0.0,9465.705,...,176958.900,176958.900,0.0,0,0.0,0.0,3.0,Active,0,0
3000394,1794451,456250,-12,181993.500,180000,171000.0,171000.0,0.0,0.0,0.000,...,171000.000,171000.000,7.0,7,0.0,0.0,0.0,Active,0,0
3611324,1794451,456250,-11,200208.915,180000,9000.0,9000.0,0.0,0.0,0.000,...,196581.915,196581.915,1.0,1,0.0,0.0,0.0,Active,0,0
3734047,1794451,456250,-9,180536.760,180000,0.0,0.0,0.0,0.0,9653.985,...,179866.260,179866.260,0.0,0,0.0,0.0,2.0,Active,0,0

In [6]:
# 總行數
row_total = credit_card_balance.shape[0]

In [11]:
# 遺失值比率
# 全部遺失值不超過20% 
nan_rows_sum = credit_card_balance.isna().sum()/row_total
max_nan_percentage = nan_rows_sum.max()
min_nan_percentage = nan_rows_sum.min()
print("最大遺失值佔比:", max_nan_percentage)
print("-"*80)
print(nan_rows_sum)

最大遺失值佔比: 0.19998062657409085
--------------------------------------------------------------------------------
SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.000000
AMT_CREDIT_LIMIT_ACTUAL       0.000000
AMT_DRAWINGS_ATM_CURRENT      0.195249
AMT_DRAWINGS_CURRENT          0.000000
AMT_DRAWINGS_OTHER_CURRENT    0.195249
AMT_DRAWINGS_POS_CURRENT      0.195249
AMT_INST_MIN_REGULARITY       0.079482
AMT_PAYMENT_CURRENT           0.199981
AMT_PAYMENT_TOTAL_CURRENT     0.000000
AMT_RECEIVABLE_PRINCIPAL      0.000000
AMT_RECIVABLE                 0.000000
AMT_TOTAL_RECEIVABLE          0.000000
CNT_DRAWINGS_ATM_CURRENT      0.195249
CNT_DRAWINGS_CURRENT          0.000000
CNT_DRAWINGS_OTHER_CURRENT    0.195249
CNT_DRAWINGS_POS_CURRENT      0.195249
CNT_INSTALMENT_MATURE_CUM     0.079482
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.000000
SK_DPD_DEF                    0.000000
dtype: float64

In [18]:
# 0的比率
zero_rows_sum = (credit_card_balance == 0).sum()/row_total
print(zero_rows_sum)
#print("-"*80)
#print(zero_rows_sum.describe())

SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.561522
AMT_CREDIT_LIMIT_ACTUAL       0.196292
AMT_DRAWINGS_ATM_CURRENT      0.694141
AMT_DRAWINGS_CURRENT          0.839370
AMT_DRAWINGS_OTHER_CURRENT    0.801540
AMT_DRAWINGS_POS_CURRENT      0.735772
AMT_INST_MIN_REGULARITY       0.502268
AMT_PAYMENT_CURRENT           0.101686
AMT_PAYMENT_TOTAL_CURRENT     0.565637
AMT_RECEIVABLE_PRINCIPAL      0.597912
AMT_RECIVABLE                 0.550428
AMT_TOTAL_RECEIVABLE          0.550383
CNT_DRAWINGS_ATM_CURRENT      0.694141
CNT_DRAWINGS_CURRENT          0.841065
CNT_DRAWINGS_OTHER_CURRENT    0.801416
CNT_DRAWINGS_POS_CURRENT      0.735772
CNT_INSTALMENT_MATURE_CUM     0.143600
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.960067
SK_DPD_DEF                    0.976736
dtype: float64

# 觀察各個欄位

# 這時候有兩條路去探索
# 0要drop掉還是怎麼補
# 哪幾個欄位可以去生成新的欄位(商業價值)

# 第一種探索 (0要drop掉還是怎麼補)

In [ ]:
# 我想做一個簡單的function去跑 
# 有什麼類別、佔比多少|遺失值比率|0的比率|最大最小值

# def check(a):
#     c= a.sort_values(by=[0],ascending=False)
#     d = c[0].unique()
#     print(c)

In [ ]:
# row全取,留第一個欄位
credit_card_balance.iloc[:,0:1]

In [19]:
#有幾種類別
MONTHS_BALANCE_Sort = credit_card_balance.sort_values(by=['MONTHS_BALANCE'],ascending=False)
MONTHS_BALANCE_Sort_Categories = MONTHS_BALANCE_Sort['MONTHS_BALANCE'].unique()
print(MONTHS_BALANCE_Sort_Categories)

[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17 -18
 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35 -36
 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49 -50 -51 -52 -53 -54
 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 -66 -67 -68 -69 -70 -71 -72
 -73 -74 -75 -76 -77 -78 -79 -80 -81 -82 -83 -84 -85 -86 -87 -88 -89 -90
 -91 -92 -93 -94 -95 -96]

In [ ]:

# 看Active佔的總比數
Boolin = credit_card_balance['NAME_CONTRACT_STATUS']=='Active'
print(Boolin.sum()/row_total)

In [32]:
# 發現描述裡"AMT_RECIVABLE"與"AMT_TOTAL_RECEIVABLE" 極度相似
matching_count = (credit_card_balance['AMT_RECIVABLE'] == credit_card_balance['AMT_TOTAL_RECEIVABLE']).sum()
print("相同的百分比:", matching_count/row_total)
print("選擇drop掉其一")
print("-"*80)
RE_NAN=credit_card_balance["AMT_RECIVABLE"].isna().sum()/row_total
RE_ZERO=(credit_card_balance["AMT_RECIVABLE"] == 0).sum()/row_total
RETOTAL_NAN=credit_card_balance["AMT_TOTAL_RECEIVABLE"].isna().sum()/row_total
RETOTAL_ZERO=(credit_card_balance["AMT_TOTAL_RECEIVABLE"] == 0).sum()/row_total
print("AMT_RECIVABLE 遺失值為 : ",RE_NAN)
print("AMT_TOTAL_RECEIVABLE 遺失值為 : ",RETOTAL_NAN)
print("-"*80)
print("AMT_RECIVABLE        0值為 : ",RE_ZERO)
print("AMT_TOTAL_RECEIVABLE 0值為 : ",RETOTAL_ZERO)
print("-"*80)
print("所以drop掉0值比較多的AMT_Recivable")

相同的百分比: 0.9970721128908276
選擇drop掉其一
--------------------------------------------------------------------------------
AMT_RECIVABLE 遺失值為 :  0.0
AMT_TOTAL_RECEIVABLE 遺失值為 :  0.0
--------------------------------------------------------------------------------
AMT_RECIVABLE        0值為 :  0.5504281943758736
AMT_TOTAL_RECEIVABLE 0值為 :  0.5503831459527246
--------------------------------------------------------------------------------
所以drop掉0值比較多的AMT_Recivable

In [ ]:
a_category_percentage = credit_card_balance.iloc[:,0:1].value_counts(normalize=True) * 100
a_category_percentage

In [ ]:
credit_card_balance.max()

In [ ]:
credit_card_balance.min()