In [10]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
credit_card_balance= pd.read_csv("credit_card_balance.csv")
#previous_application = pd.read_csv("previous_application.csv")

# SK_ID_PREV : 貸款ID 
# SK_ID_CURR : 客戶ID
# MONTHS_BALANCE :

In [5]:
credit_card_balance.sort_values(by=['SK_ID_CURR','SK_ID_PREV'])
#384萬筆資料，23欄位

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
584804,1489396,100006,-1,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248506,1794451,456250,-7,174435.885,180000,0.0,0.0,0.0,0.0,9240.705,...,174435.885,174435.885,0.0,0,0.0,0.0,4.0,Active,0,0
2985617,1794451,456250,-8,177219.000,180000,0.0,0.0,0.0,0.0,9465.705,...,176958.900,176958.900,0.0,0,0.0,0.0,3.0,Active,0,0
3000394,1794451,456250,-12,181993.500,180000,171000.0,171000.0,0.0,0.0,0.000,...,171000.000,171000.000,7.0,7,0.0,0.0,0.0,Active,0,0
3611324,1794451,456250,-11,200208.915,180000,9000.0,9000.0,0.0,0.0,0.000,...,196581.915,196581.915,1.0,1,0.0,0.0,0.0,Active,0,0
3734047,1794451,456250,-9,180536.760,180000,0.0,0.0,0.0,0.0,9653.985,...,179866.260,179866.260,0.0,0,0.0,0.0,2.0,Active,0,0

In [7]:
#該欄位空值佔總比數幾%
credit_card_balance.isna().sum()/credit_card_balance.shape[0]

SK_ID_PREV                    0.000000
SK_ID_CURR                    0.000000
MONTHS_BALANCE                0.000000
AMT_BALANCE                   0.000000
AMT_CREDIT_LIMIT_ACTUAL       0.000000
AMT_DRAWINGS_ATM_CURRENT      0.195249
AMT_DRAWINGS_CURRENT          0.000000
AMT_DRAWINGS_OTHER_CURRENT    0.195249
AMT_DRAWINGS_POS_CURRENT      0.195249
AMT_INST_MIN_REGULARITY       0.079482
AMT_PAYMENT_CURRENT           0.199981
AMT_PAYMENT_TOTAL_CURRENT     0.000000
AMT_RECEIVABLE_PRINCIPAL      0.000000
AMT_RECIVABLE                 0.000000
AMT_TOTAL_RECEIVABLE          0.000000
CNT_DRAWINGS_ATM_CURRENT      0.195249
CNT_DRAWINGS_CURRENT          0.000000
CNT_DRAWINGS_OTHER_CURRENT    0.195249
CNT_DRAWINGS_POS_CURRENT      0.195249
CNT_INSTALMENT_MATURE_CUM     0.079482
NAME_CONTRACT_STATUS          0.000000
SK_DPD                        0.000000
SK_DPD_DEF                    0.000000
dtype: float64